CREATE DATABASE BDJOIN
GO
USE BDJOIN
GO
CREATE TABLE CATEGORIA (
	CODCATEGORIA INT NOT NULL PRIMARY KEY, 
	NOMECATEGORIA VARCHAR(30)
)
GO
CREATE TABLE FORNECEDOR (
	CODFORNECEDOR INT NOT NULL PRIMARY KEY,
	NOMEFORNECEDOR VARCHAR(50)
)
GO
CREATE TABLE PRODUTO (
	CODPRODUTO INT IDENTITY NOT NULL PRIMARY KEY, 
	NOMEPRODUTO VARCHAR(30), 
	CODCATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA (CODCATEGORIA), 
	CODFORNECEDOR INT FOREIGN KEY REFERENCES FORNECEDOR (CODFORNECEDOR), 
	QUANTIDADE INT, 
	VALORUNITARIO DECIMAL(10,2))
GO

--Cadastros Tabela Categoria
INSERT INTO CATEGORIA VALUES (1,'DOCE')
INSERT INTO CATEGORIA VALUES (2,'SALGADO')
INSERT INTO CATEGORIA VALUES (3,'BEBIDA')
INSERT INTO CATEGORIA VALUES (4,'LIMPEZA')
INSERT INTO CATEGORIA VALUES (5,'CONGELADOS')
INSERT INTO CATEGORIA VALUES (6,'LEGUMES')
GO

--Cadastros Tabela Fornecedor
INSERT INTO FORNECEDOR VALUES (1,'FRUTIQUELLO')
INSERT INTO FORNECEDOR VALUES (2,'KIBOM')
INSERT INTO FORNECEDOR VALUES (3,'Coca Cola')
INSERT INTO FORNECEDOR VALUES (4,'Tramontina')
INSERT INTO FORNECEDOR VALUES (5,'Dell')
INSERT INTO FORNECEDOR VALUES (6,'HP')
INSERT INTO FORNECEDOR VALUES (7,'Dove')
INSERT INTO FORNECEDOR VALUES (8,'Lacta')

--Cadastros Tabela Produto
INSERT INTO PRODUTO VALUES ('REFRIGERANTE COCA COLA',3,3,15,2.50)
INSERT INTO PRODUTO VALUES ('SABONETE PROTEX',4,7,50,1.99)
INSERT INTO PRODUTO VALUES ('CHOCOLATE SHOT LACTA',1,8,10,5.89)
INSERT INTO PRODUTO VALUES ('BOLACHA',1,8,3.50,3)
INSERT INTO PRODUTO VALUES ('FRIGIDEIRA TRAMONTINA',NULL,2,3,15.60)
INSERT INTO PRODUTO VALUES ('FACA TRAMONTINA',NULL,1,5,35.00)
INSERT INTO PRODUTO VALUES ('JOGO DE PRATOS',NULL,1,1,155.00)
GO

--Exercícios Junção de Tabelas

1 - Usando o INNER JOIN exiba os seguintes atributos:
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
valorunitario	-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:
go
select CODPRODUTO, NOMEPRODUTO, VALORUNITARIO, NOMECATEGORIA
from PRODUTO inner join CATEGORIA
on PRODUTO.CODCATEGORIA = CATEGORIA.CODCATEGORIA
GO


2 - Usando o INNER JOIN exiba os seguintes atributos:
NomeProduto		-> PRODUTO
NomeFornecedor	-> FORNECEDOR
--Código:

go
select NOMEPRODUTO, NOMEFORNECEDOR
from PRODUTO inner join FORNECEDOR
on FORNECEDOR.CODFORNECEDOR = PRODUTO.CODFORNECEDOR
GO


3 - Usando o LEFT JOIN exiba os seguintes atributos:
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:


select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA
from PRODUTO left join CATEGORIA
on CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA


4 - Usando o RIGHT JOIN exiba os seguintes atributos:
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:

select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA
from PRODUTO right join CATEGORIA
on CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA




5 - Usando o FULL JOIN exiba os seguintes atributos:
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:

select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA
from PRODUTO FULL JOIN CATEGORIA
on CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA



6 - Exibir os seguintes atributos. Nessa junção deverão ser exibidos os PRODUTOS QUE NÃO TEM CATEGORIAS ADICIONADAS 
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:

select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA
from PRODUTO LEFT join CATEGORIA
on CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA where CATEGORIA.NOMECATEGORIA IS NULL 



7 - Usando o INNER JOIN exiba os seguintes atributos:
Exibir os seguintes campos:
NomeProduto
NomeCategoria
Quantidade

Obs: Apenas dos produtos que forem da categoria: Doce
--Código:

select QUANTIDADE, NOMEPRODUTO, NOMECATEGORIA
from PRODUTO inner join CATEGORIA
on CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA
where CATEGORIA.CODCATEGORIA = 1



8 - Usando o INNER JOIN exiba os seguintes atributos:
Exibir os seguintes campos:
CodProduto
NomeProduto
NomeFornecedor

Obs: Apenas dos produtos que tiverem preço acima de 10.00
--Código:

select CODPRODUTO, NOMEPRODUTO, NOMEFORNECEDOR
from PRODUTO inner join FORNECEDOR
on PRODUTO.CODFORNECEDOR = FORNECEDOR.CODFORNECEDOR
where PRODUTO.QUANTIDADE > 10.00


9 - Usando o INNER JOIN exiba os seguintes atributos:
Exibir os seguintes campos:
NomeProduto
NomeCategoria
NomeFornecedor
--Código: 

select NOMECATEGORIA, NOMEPRODUTO, NOMEFORNECEDOR
from PRODUTO 
inner join FORNECEDOR
ON PRODUTO.CODFORNECEDOR = FORNECEDOR.CODFORNECEDOR
inner join CATEGORIA
ON PRODUTO.CODCATEGORIA = CATEGORIA.CODCATEGORIA


10 - Usando o LEFT JOIN exiba os seguintes atributos:
Exibir os seguintes campos: 
NomeProduto
NomeCategoria
Quantidade

OBS: Os produtos que tem ou não categorias vinculadas. 
Apenas produtos com quantidade acima de 5
--Código:

select NOMECATEGORIA, NOMEPRODUTO, QUANTIDADE
from PRODUTO left join CATEGORIA
ON PRODUTO.CODCATEGORIA = CATEGORIA.CODCATEGORIA
where PRODUTO.QUANTIDADE > 5


11 - Usando o RIGHT JOIN exiba os seguintes atributos:
Exibir os seguintes campos:
NomeProduto
NomeFornecedor
Quantidade
Preco

Obs: Os produtos que tem ou não fornecedores vinculados
--Código:


select QUANTIDADE, NOMEPRODUTO, NOMEFORNECEDOR, VALORUNITARIO
from PRODUTO right join FORNECEDOR
ON PRODUTO.CODFORNECEDOR = FORNECEDOR.CODFORNECEDOR


